DEBUG: true
SECRET_KEY: 'Django secret key'
ALLOWED_HOSTS: 
  - 'localhost'
  - '*'
SWAGGER_TITLE: voyage_backend
SWAGGER_DESCRIPTION: 'API for bot_mem'

DATABASE_NAME: './src/db.sqlite3'
SHELVE_NAME: 'shelve.db'
SHELVE_LEVEL: 'shelve_level.db'
